add configuration for running local shellcheck script
felipefzdz/gradle-shellcheck-plugin pull request #1
Opened 2021-04-26 03:45 UTC by cnygardtw

- avoid running via docker image, use (kotlin) `useDocker.set(false)`
- configure path to shellcheck binary via shellcheckBinary property
- add tests for all current docker-based tests
- clean up config property definitions, add config for image, image version
- upgrade to gradle v7.0
- update docs
- bump version to 1.1.0

2021-04-26 13:02 UTC, felipefzdz commented
Thanks a lot for the PR! I'll review it asap.

2021-04-26 14:46 UTC, felipefzdz requested changes
Thanks for tackling this! Left some comments.

2021-04-26 14:46 UTC, felipefzdz commented on README.adoc
> +    continueBuildOnFailure = true
`continueBuildOnFailure` and `showViolations` are breaking changes so they shouldn't be part of a minor release, like 1.1. Even if we could argue that they're an improvement from the previous names, I don't think that they should require a major release. `continueBuildOnFailure` refactor was also incomplete, as there are some `ignoreFailures` references still around. Would you mind reverting this refactor?

2021-04-26 14:46 UTC, felipefzdz commented on README.adoc
> +    shellcheckImage = "koalaman/shellcheck-alpine"
Why is `shellcheckImage` now configurable? i.e. is it any valuable scenario where we see a user providing something like `pipelinecomponents/shellcheck`? I'm not familiar with the inner details of the different docker images wrapping Shellcheck, but if there's no known value, I'd refrain adding this configuration.

2021-04-26 14:46 UTC, felipefzdz commented on README.adoc
> +* useDocker - Whether to use docker image (true) or local shellcheck binary (false)
Could you please add the default here? true, in this case.

2021-04-26 14:46 UTC, felipefzdz commented on shellcheck/src/functionalTest/groovy/com/felipefzdz/gradle/shellcheck/ShellcheckPluginCacheTest.groovy
> +        //localGradleDirectory.exists()
Why this commented line?

2021-04-26 14:46 UTC, felipefzdz commented on shellcheck/src/functionalTest/groovy/com/felipefzdz/gradle/shellcheck/ShellcheckPluginCacheTest.groovy
> +    useDocker.set(false)
(local binary)  tests, i.e. the ones that contain this line on the to be tested build.file are not reproducible anymore, in the sense that they require `/usr/local/bin/shellcheck` to be installed on the machine executing the tests, being a local machine or a CI agent.

I don't think that we should get too smart here, trying to install it if not available, but a message stating the reason of this to fail would be appreciated. Therefore, I'd organize the tests in two classes at least, the ones that are portable (Docker based ones) and the local that are not. On the latter we could add a single comment opening the class, or even an `@IgnoreIf` that would check for `/usr/local/bin/shellcheck` existence. Then if we decide to add CI support for this project we won't be blocked by these failing tests.

2021-04-26 14:46 UTC, felipefzdz commented on shellcheck/src/main/java/com/felipefzdz/gradle/shellcheck/Shellcheck.java
> +//    @Optional
Why these `@Optional` commented out?

2021-04-29 10:03 UTC, felipefzdz commented
@cnygardtw I'll merge this and do the suggested changes myself on the `main` branch. I'll ping you when this is released. Thanks again for the PR :)

2021-04-29 10:04 UTC, merged

2021-04-30 14:21 UTC, felipefzdz commented
@cnygardtw just to let you know that this has been released, along with the ability of self install the binary.

Thanks!

2021-05-12 20:19 UTC, cnygardtw commented
Thanks, appreciate you picking this up.  Sorry I didn't have time at the moment to push the updates.   I'll check it out.

2021-05-12 20:22 UTC, cnygardtw commented on README.adoc
> +    continueBuildOnFailure = true
Just to follow up, I was following the latest guidance from Gradle re: deprecated Convention mapping, but the parent class still used it.  So I had to rename the property to work around that.  I was not trying to improve the names or break compatibility...

2021-05-12 20:23 UTC, cnygardtw commented on README.adoc
> +    shellcheckImage = "koalaman/shellcheck-alpine"
If an org has restrictions on using random docker images from the web, they could configure an internally-created shellcheck image instead.  I think it has value, and providing a default does no harm.

2021-05-12 20:26 UTC, cnygardtw commented on shellcheck/src/functionalTest/groovy/com/felipefzdz/gradle/shellcheck/ShellcheckPluginCacheTest.groovy
> +        //localGradleDirectory.exists()
honestly not sure, probably cruft

2021-05-12 20:28 UTC, cnygardtw commented on shellcheck/src/functionalTest/groovy/com/felipefzdz/gradle/shellcheck/ShellcheckPluginCacheTest.groovy
> +    useDocker.set(false)
Sounds reasonable. I was assuming that the docker image which does the build/test in CI would need to have shellcheck installed locally (and therefore was outside my ability to change).

2021-05-12 20:30 UTC, cnygardtw commented on shellcheck/src/main/java/com/felipefzdz/gradle/shellcheck/Shellcheck.java
> +//    @Optional
Should probably have removed them.  Providing default values in the property conventions means they don't need to be optional, and supplied defaults makes the code simpler by not dealing with missing values.

2021-05-13 19:42 UTC, felipefzdz commented on README.adoc
> +    continueBuildOnFailure = true
You're right. I misunderstood the change. I'll tackle that in the future!

2021-05-13 19:43 UTC, felipefzdz commented on README.adoc
> +    shellcheckImage = "koalaman/shellcheck-alpine"
Makes sense, thanks for the explanation. I'll put it back.